
# Operator Interface
DRIVER_CONTROLLER_PORT = 0
OPERATOR_CONTROLLER_PORT = 1

# Drive
LEFT_LEADER_ID = 1
LEFT_FOLLOWER_ID = 2
RIGHT_LEADER_ID = 3
RIGHT_FOLLOWER_ID = 4

DRIVE_MOTOR_CURRENT_LIMIT = 60

DRIVE_PEAK_CURRENT = 35 #amps
DRIVE_PEAK_DURATION = 2000 #milliseconds
DRIVE_CONTINUOUS_CURRENT = 30 #amps

# Roller
ROLLEY_THINGEY_ID = 5
ROLLEY_THINGEY_CURRENT_LIMIT = 60
ROLLEY_THINGEY_VCOMP = 10
ROLLEY_THINGEY_EJECT_SPEED = -0.44

# AutomaticPneumatic
PRESSURE_HIGH_VALUE = 115
PRESSURE_LOW_VALUE = 93
AUTOMATICPNEUMATICS_COMPRESSOR_ID = 12
AUTOMATICPNEUMATICS_SOLENOID_CHANNEL = 0
AUTOMATICPNEUMATICS_SOLENOID_CHANNEL_1 = 1

# Rolley Arm
ROLLEYARM_MOTOR_ID = 7
ROLLEYARM_MOTOR_CURRENT_LIMIT = 60
ROLLEYARM_MOTOR_VCOMP = 10